apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-java-project
  template:
    metadata:
      labels:
        app: rest-java-project
    spec:
      containers:
        - name: java-rest
          image: kenag/rest-java-project:latest
          ports:
            - containerPort: 8080

            
