apiVersion: v1
kind: Service
metadata:
      name: my-sevice
      labels:
        app: rest-java-project
        tier: backend
spec:
      type: NodePort
      ports:
      - port: 8080
      selector:
        app: rest-java-project
        tier: backend